import PageHeader from "../components/PageHeader";
import StatCard from "../components/StatCard";
import Callout from "../components/Callout";
import FigureCard from "../components/FigureCard";
import PriorityChart from "../components/PriorityChart";
import detectionSummary from "../data/detection_summary.json";
import priorityCounts from "../data/priority_counts.json";
import modelComparison from "../data/model_comparison.json";
import { formatNumber } from "../utils/format";

export default function Overview() {
  const selected = modelComparison.find((m) => m.model === "One-Class SVM");

  return (
    <div>
      <PageHeader eyebrow="Anomaly Detector · PMAY-U 2025">
        <h1>Unsupervised anomaly detection &amp; investigation support</h1>
        <p>
          This system identifies statistically unusual observations in the
          PMAY-U 2025 dataset and ranks them for further investigation. It
          does not determine, and is not evidence of, corruption or
          wrongdoing.
        </p>
      </PageHeader>

      <div className="section">
        <div className="grid grid-4">
          <StatCard
            value={formatNumber(detectionSummary["Total observations"])}
            label="Total records"
          />
          <StatCard
            value={formatNumber(detectionSummary["Anomalous observations"])}
            label="Anomaly candidates"
            accent
          />
          <StatCard
            value={formatNumber(detectionSummary["Normal observations"])}
            label="Normal records"
          />
          <StatCard
            value={detectionSummary["Anomaly percentage"]}
            label="Anomaly rate"
          />
        </div>
      </div>

      <div className="section grid grid-2">
        <div className="card">
          <h3>Anomaly score distribution</h3>
          <p className="muted" style={{ fontSize: "var(--text-sm)" }}>
            Normal and anomalous observations, separated by the selected
            One-Class SVM model's anomaly score.
          </p>
          <FigureCard
            src="/figures/anomaly_score_distribution.png"
            alt="Histogram of anomaly scores for normal and anomalous observations"
            caption="Generated by the analysis pipeline"
          />
        </div>

        <div className="card">
          <h3>Investigation priority</h3>
          <p className="muted" style={{ fontSize: "var(--text-sm)" }}>
            Anomaly candidates are grouped into priority tiers by how
            unusual their score is, relative to the full dataset.
          </p>
          <PriorityChart data={priorityCounts} />
        </div>
      </div>

      <div className="section grid grid-2">
        <div className="card">
          <h3>Model selection summary</h3>
          <p>
            Three unsupervised methods were evaluated — Isolation Forest,
            Local Outlier Factor, and One-Class SVM. Because the dataset has
            no ground-truth corruption labels, the model was chosen by
            comparing how stable each method's anomaly rankings were under
            repeated perturbation, not by accuracy.
          </p>
          <p style={{ marginBottom: 0 }}>
            <strong>{selected.model}</strong> ({selected.configuration}) was
            selected, with an observed top-5% ranking stability of{" "}
            <span className="mono">{selected.stability.toFixed(4)}</span>.
          </p>
        </div>

        <div className="card">
          <h3>How this works, briefly</h3>
          <p style={{ marginBottom: 0 }}>
            Six numerical fields — investment, central assistance, and
            houses sanctioned, grounded and completed — are cleaned,
            transformed, and scaled, then passed to a One-Class SVM that
            flags observations sitting far outside the typical pattern.
            Flagged records are ranked and given an investigation priority.
            See{" "}
            <a href="/methodology">Methodology</a> for the full pipeline.
          </p>
        </div>
      </div>

      <Callout>
        An anomaly indicates statistical unusualness and does not establish
        corruption or wrongdoing. Results are intended to support, not
        replace, human and administrative investigation.
      </Callout>
    </div>
  );
}
