// Wraps a static research figure (PNG generated by the Python pipeline)
// with a caption. This is used instead of redrawing charts so the
// dashboard always shows exactly what the analysis pipeline produced.
export default function FigureCard({ src, alt, caption, tag = "Figure" }) {
  return (
    <figure className="figure-card">
      <img src={src} alt={alt} loading="lazy" />
      <figcaption className="figure-caption">
        <span>{caption}</span>
        <span className="figure-caption-tag">{tag}</span>
      </figcaption>
    </figure>
  );
}
